src/public_settings.h:
  constants:
    # EPOCH: 152
    # TICK: 21180000
    TESTNET_EPOCH_DURATION: 7000
    ADDON_TX_STATUS_REQUEST: 1
    START_NETWORK_FROM_SCRATCH: 1
    NUMBER_OF_SOLUTION_PROCESSORS: 2
    TARGET_TICK_DURATION: 7000
    TRANSACTION_SPARSENESS: 4
    MAX_NUMBER_OF_TICKS_PER_EPOCH: '(((((60 * 60 * 24 * 1) / (TARGET_TICK_DURATION / 1000)) + NUMBER_OF_COMPUTORS - 1) / NUMBER_OF_COMPUTORS) * NUMBER_OF_COMPUTORS)'
src/private_settings.h:
  constants:
    # Logs
    LOG_QU_TRANSFERS: 1
    LOG_BURNINGS: 1
    LOG_DUST_BURNINGS: 1
    LOG_SPECTRUM_STATS: 1
    LOG_ASSET_ISSUANCES: 1
    LOG_ASSET_OWNERSHIP_CHANGES: 1
    LOG_ASSET_POSSESSION_CHANGES: 1
    LOG_ASSET_OWNERSHIP_MANAGING_CONTRACT_CHANGES: 1
    LOG_ASSET_POSSESSION_MANAGING_CONTRACT_CHANGES: 1
    LOG_CONTRACT_ERROR_MESSAGES: 1
    LOG_CONTRACT_WARNING_MESSAGES: 1
    LOG_CONTRACT_INFO_MESSAGES: 1
    LOG_CONTRACT_DEBUG_MESSAGES: 1
    LOG_CUSTOM_MESSAGES: 1
    # Autosave mode
    TICK_STORAGE_AUTOSAVE_MODE: 0
    TICK_STORAGE_AUTOSAVE_TICK_PERIOD: 300
src/qubic.cpp:
  constants:
    PORT: 31841
