src/public_settings.h:
  constants:
    ADDON_TX_STATUS_REQUEST: 1
    START_NETWORK_FROM_SCRATCH: 1
    NUMBER_OF_SOLUTION_PROCESSORS: 1
    MAX_NUMBER_OF_TICKS_PER_EPOCH: '(((((60 * 60 * 20 * 1) / (TARGET_TICK_DURATION / 1000)) + NUMBER_OF_COMPUTORS - 1) / NUMBER_OF_COMPUTORS) * NUMBER_OF_COMPUTORS)'
src/private_settings.h:
  constants:
    # Logs
    ENABLE_STANDARD_LOGGING: 1
    ENABLE_SMART_CONTRACT_LOGGING: 1
    # Autosave mode
    TICK_STORAGE_AUTOSAVE_MODE: 0
    TICK_STORAGE_AUTOSAVE_TICK_PERIOD: 300
src/qubic.cpp:
  constants:
    PORT: 21841


