src/public_settings.h:
  constants:
   # EPOCH: 159
   # TICK: 23480000
    TESTNET_EPOCH_DURATION: 10000
    ADDON_TX_STATUS_REQUEST: 1
    START_NETWORK_FROM_SCRATCH: 1
    NUMBER_OF_SOLUTION_PROCESSORS: 2
    TARGET_TICK_DURATION: 7000
    TRANSACTION_SPARSENESS: 4
    # TARGET_TICK_VOTE_SIGNATURE: 0xFFFFFFFFU
src/private_settings.h:
  constants:
    # Logs
    ENABLE_STANDARD_LOGGING: 1
    ENABLE_SMART_CONTRACT_LOGGING: 1
    # Autosave mode
    TICK_STORAGE_AUTOSAVE_MODE: 0
    TICK_STORAGE_AUTOSAVE_TICK_PERIOD: 300
src/qubic.cpp:
  constants:
    PORT: 31841
